name: Build ImmortalWrt-mt798x

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true

      - name: Setup dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          export LC_ALL="en_US.UTF-8"
          sudo dpkg-reconfigure locales
          sudo apt-get update -y
          sudo apt-get full-upgrade -y
          sudo apt-get install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
            bzip2 ccache clang clangd cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
            g++-multilib git gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev libglib2.0-dev \
            libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5 libncursesw5-dev libreadline-dev \
            libssl-dev libtool lld lldb lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 \
            python3 python3-pip python3-ply python-docutils qemu-utils re2c rsync scons squashfs-tools subversion swig \
            texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev

      - name: Clone source code
        env: 
          REPO_URL: https://github.com/hanwckf/immortalwrt-mt798x.git
          REPO_BRANCH: openwrt-21.02
        run: |
          git clone --depth=1 $REPO_URL -b $REPO_BRANCH

      - name: Update & Install feeds
        working-directory: ./immortalwrt-mt798x
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        
      - name: Download package
        working-directory: ./immortalwrt-mt798x
        run: |
          make download -j$(nproc)

      - name: Build firmware
        working-directory: ./immortalwrt-mt798x
        run: |
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s

      - name : Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-mt798x
          path: immortalwrt-mt798x/bin
